### ISSUE TITLE
Use new taplo

### ISSUE THREAD

**Issue by kkiyama117** [kkiyama117/coc-toml#6]

**Comment by GopherJ** [comment]
also we need to use taplo compiled using release mode

**Comment by tamasfe** [comment]
I've published the LSP as a separate package [on NPM](https://www.npmjs.com/package/@taplo/lsp) so you don't have to build it manually, and should be easier to use.

I added proper typescript typings as well so that you more or less know what to expect, an example usage is [here](https://github.com/tamasfe/taplo/blob/master/js/vscode/src/server.ts), in the VSCode extension (unpublished).

I'm planning to write some additional docs about it on the site, but I'm not quite there yet.

**Comment by tamasfe** [comment]
[here](https://taplo.tamasfe.dev/lsp/) it is, I've tested it in the VSCode extension, the next published version of it will use this library as well.

**Comment by kkiyama117** [comment]
@tamasfe thank you for your advice, I have little time to write code but will use npm's one and refactor the structure of this repo next year

**Comment by kkiyama117** [comment]
Solved at `v1.0.3`
