### ISSUE TITLE
coc-toml.formatter.alignEntries doesn't work anymore

### ISSUE THREAD

**Issue by GopherJ** [kkiyama117/coc-toml#9]

**Comment by GopherJ** [comment]
I just found that latest version's `coc-toml.formatter.alignEntries` is now by default false and it doesn't work when I change it to `true`, anyone with the same issue?

**Comment by kkiyama117** [comment]
Thanks for your report.
I find same probrem is occurred in my computer, and this bug may be caused by the connection not working correctly between `coc-toml` and `taplo`, lsp implementation this plugin uses.

I checked
- configuration parsed by coc.nvim is correct
- original vscode extension is running correctly
- format with options may work correctly if some invalid grammer is included in toml
- any other commands (including  at this plugin may be working correctly.

But I'm not found why this behaviors appear now, so please wait a little longer until I find it and let me know if anything comes to your attention.

**Comment by kkiyama117** [comment]
@GopherJ 
This may be fixed by `v0.1.6`. please upload and try new one. If bugs are remained, please reopen this issue.

**Comment by GopherJ** [comment]
@kkiyama117 tested fixed, thanks!
